//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Section1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Course
    {
        public int CourseID { get; set; }
        [DisplayName("Course Name")]
        public string CourseName { get; set; }
        [DisplayName("Duration in Months")]
        public Nullable<int> DurationInMonths { get; set; }
        [DisplayName("Courses of Degree")]
        public string CoursesPartOfDegree { get; set; }
        public string Degree { get; set; }

    }

    public enum ListOfCourses
    {
        Theatre,
        Communication,
        Music,
        Art,
        ComputerScience,
        Business,
        Biology,
        Nursing
    }





}
