//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Section1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Degree
    {
        public int DegreeID { get; set; }
        [DisplayName("Degree Name:")]
        public string DegreeName { get; set; }
        [DisplayName("Duration in Years:")]
        public Nullable<int> DegreeDuringInYears { get; set; }
        [DisplayName("Course of the Degree:")]
        public string CoursesOfDegree { get; set; }

        
        public int UserID { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }

    
    }

  
}
