//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Section3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Forenames { get; set; }
        public string Surnames { get; set; }
        public string EmailAddress { get; set; }
        public string DateOfBirth { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string DegreeSt { get; set; }
        public Nullable<int> LecturerID { get; set; }
    
        public virtual Lecturer Lecturer { get; set; }
    }
    public enum SPosition
    {
        Student
    }
}
